<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	<title>Function try_catch_finally</title>

	<link rel="stylesheet" href="resources/bootstrap.min.css?973e37a8502921d56bc02bb55321f45b072b6f71">
	<link rel="stylesheet" href="resources/style.css?4bb6454ea5dbd127d475d6edffaf8eda279d79a3">

</head>

<body>
	<nav id="navigation" class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<a href="index.html" class="navbar-brand">Overview</a>
			</div>
			<div class="collapse navbar-collapse">

                <form id="search" class="navbar-form navbar-left" role="search">
                    <input type="hidden" name="cx" value="">
                    <input type="hidden" name="ie" value="UTF-8">
                    <div class="form-group">
                        <input type="text" name="q" class="search-query form-control" placeholder="Search">
					</div>
				</form>

				<ul class="nav navbar-nav">
					<li>
<span>Package</span>					</li>
					<li class="active">
<span>Function</span>					</li>





				</ul>
			</div>
		</div>
	</nav>

	<div id="left">
	<div id="menu">

		<div id="groups">
				<h3>Packages</h3>
			<ul>
					<li>
						<a href="package-array.html">
							array						</a>
							</li>
					<li>
						<a href="package-callable.html">
							callable						</a>
							</li>
					<li>
						<a href="package-class.html">
							class						</a>
							</li>
					<li>
						<a href="package-filesystem.html">
							filesystem						</a>
							</li>
					<li>
						<a href="package-string.html">
							string						</a>
							</li>
					<li>
						<a href="package-syntax.html">
							syntax						</a>
							</li>
					<li>
						<a href="package-var.html">
							var						</a>
							</li>
			</ul>
		</div>


		<div id="elements">





			<h3>Functions</h3>
			<ul>
				<li><a href="function-returns.html">returns<small class="summary">: 引数をそのまま返す</small></a></li>
				<li><a href="function-throws.html">throws<small class="summary">: throw の関数版</small></a></li>
				<li><a href="function-try_catch.html">try_catch<small class="summary">: try ～ catch 構文の関数版</small></a></li>
				<li class="active"><a href="function-try_catch_finally.html">try_catch_finally<small class="summary">: try ～ catch ～ finally 構文の関数版</small></a></li>
			</ul>
		</div>
	</div>
</div>

<div id="splitter"></div>

<div id="right">
	<div id="rightInner">
<div id="content" class="function">
	<h1>Function try_catch_finally</h1>


	<div class="description">
	<p>try ～ catch ～ finally 構文の関数版</p>

<p>php &lt; 5.5 にはないし、例外機構構文が冗長なことがまれによくあるはず。</p>

<p>Example:</p>

<pre><span class="php-var">$ex</span> = <span class="php-keyword1">new</span> \Exception(<span class="php-quote">'try_catch'</span>);
<span class="php-keyword2">assert</span>(try_catch(<span class="php-keyword1">function</span>() <span class="php-keyword1">use</span> (<span class="php-var">$ex</span>) { <span class="php-keyword1">throw</span> <span class="php-var">$ex</span>; }) === <span class="php-var">$ex</span>);</pre>
	</div>


	<div class="panel panel-default">
        <div class="panel-heading"><h2>Parameters summary</h2></div>
		<table class="summary table table-bordered" id="parameters">
		<tr id="$try">
			<td class="name"><code>callable</code></td>
			<td class="value"><code><var>$try</var></code></td>
			<td>try ブロッククロージャ</td>
		</tr>
		<tr id="$catch">
			<td class="name"><code>callable</code></td>
			<td class="value"><code><var>$catch</var> = <span class="php-keyword1">null</span></code></td>
			<td>catch ブロッククロージャ</td>
		</tr>
		<tr id="$finally">
			<td class="name"><code>callable</code></td>
			<td class="value"><code><var>$finally</var> = <span class="php-keyword1">null</span></code></td>
			<td>finally ブロッククロージャ</td>
		</tr>
		</table>
	</div>

	<div class="panel panel-default">
        <div class="panel-heading"><h2>Return value summary</h2></div>
		<table class="summary table table-bordered" id="returns">
		<tr>
			<td class="name"><code>
				Exception|mixed
			</code></td>
			<td>
				例外が飛ばなかったら $try ブロックの返り値、飛んだなら $catch の返り値（デフォルトで例外オブジェクト）
			</td>
		</tr>
		</table>
	</div>


	<div class="alert alert-info">
		
		<b>Package:</b> <a href="package-syntax.html">syntax</a><br>
		<b>Located at</b>
		<a href="source-function-try_catch_finally.html#69-109" title="Go to source code">
			syntax.php
		</a><br>
	</div>

</div>
	</div>

	<div id="footer">
		 API documentation generated by <a href="http://apigen.org">ApiGen</a>
	</div>
</div>
<script src="resources/combined.js?64829dd0598cd54a3fd46ce58f8efe7e2fac9ecc"></script>
<script src="elementlist.js?126bd6c95b8435693cf10370e961aa6442ab73c9"></script>
</body>
</html>
